//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BackgroundRandomizer.rc
//
#define ID_CANCEL                       2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BACKGROUNDRANDOMIZER_DIALOG 102
#define IDS_STRING_REGCOST_NEW          102
#define IDS_STRING_EXPIRATION_TRIAL     103
#define IDS_THANK_YOU                   104
#define IDS_INVALID_USERNAME_LICENSE    105
#define IDS_FAILURE_GETWINDIR           106
#define IDS_REGISTRY_KEY                107
#define IDS_TRIAL_NOTICE                108
#define IDS_EXPIRED_NOTICE              109
#define IDR_MAINFRAME                   128
#define IDR_MENU_TRAY_POPUP             130
#define IDD_DIALOG_BG_RAND_PARENT       131
#define IDR_ICON_WORKING                132
#define IDR_ICON_CHANGE_REQUEST         133
#define IDB_BITMAP_CREDIT_CARDS         135
#define IDD_DIALOG_REGISTER             136
#define IDD_DIALOG_MANAGE_BLOCKED_IMAGES 137
#define IDD_DIALOG_ADJUST_IMAGE_PROPERTIES 138
#define IDI_ICON_ROTATE_CLOCK           142
#define IDI_ICON_ROTATE_COUNTER         143
#define IDC_CHECK_ENABLE_RANDOMIZATION  1000
#define IDC_LIST_DIRECTORIES            1001
#define IDC_BUTTON_ADD                  1002
#define IDC_BUTTON_REMOVE               1003
#define IDC_CHECK_DONT_DUPLICATE_IMAGES 1004
#define IDC_CHECK_RESIZE_TO_FILL_DESKTOP 1005
#define IDC_CHECK_MAINTAIN_ASPECT_RATIO 1006
#define IDC_COMBO_ASPECT_RATIO_MODE     1011
#define IDC_CHECK_MATCH_SCREEN_ORIENTATION 1012
#define IDC_COMBO_BACKGROUND_INTERVAL   1013
#define IDC_STATIC_REGISTER             1014
#define IDC_STATIC_CREDIT_CARDS         1015
#define IDC_STATIC_EMAIL                1016
#define IDC_STATIC_WEB_SITE             1017
#define IDC_EDIT_USERNAME               1018
#define IDC_BUTTON_MANAGE_BLOCKED_IMAGES 1018
#define IDC_EDIT_LICENSE                1019
#define IDC_LIST_BLOCKED_IMAGES         1019
#define IDC_BUTTON_CANCEL               1020
#define IDC_BUTTON_ALLOW_IMAGE_AGAIN    1020
#define IDC_STATIC_EXPIRATION           1021
#define IDC_STATIC_PREVIEW              1021
#define IDC_STATIC_NOTICE               1022
#define IDC_STATIC_SCREEN_MODE          1022
#define IDC_STATIC_REGCOST              1023
#define IDC_STATIC_REGISTER_CARDS       1024
#define IDC_COMBO_AUTO_ROTATE_TO_MATCH_SCREEN 1024
#define IDC_STATIC_WEBSITE              1025
#define IDC_BUTTON_ROTATE               1025
#define IDC_BUTTON_FLIP                 1026
#define IDC_BUTTON_MIRROR               1027
#define IDC_EDIT_FILENAME               1028
#define IDC_BUTTON_ROTATE_COUNTER       1029
#define ID_MENU_CHANGEIMAGENOW          32771
#define ID_MENU_TERMINATE               32772
#define ID_MENU_ABOUT                   32773
#define ID_MENU_SETTINGS                32774
#define ID_MENU_REGISTRATION            32775
#define ID_MENU_DONTSHOWTHISIMAGEAGAIN  32776
#define ID_MENU_ROTATECURRENTIMAGE_CLOCKWISE90 32778
#define ID_MENU_ROTATECURRENTIMAGE_FLIPVERTICALLY 32779
#define ID_MENU_ROTATECURRENTIMAGE_COUNTERCLOCKWISE90 32780
#define ID_MENU_ROTATECURRENTIMAGE_MIRROR 32781
#define ID_MENU_ROTATECURRENTIMAGE_FLIP 32782
#define ID_MENU_SLIDESHOW               32783
#define ID_MENU_ADJUSTCURRENTIMAGE      32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
